In [1]:
from scipy.io import loadmat
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mne

In [2]:
mat1 = loadmat('sub-01/ProcessedData/data_ica.mat', squeeze_me=True)

In [3]:
mat1.keys()

dict_keys(['__header__', '__version__', '__globals__', 'hdr', 'fsample', 'trialinfo', 'sampleinfo', 'trial', 'time', 'label', 'cfg'])

In [4]:
mat1['trialinfo']

array([[      2,       3,       6, ...,   50308,       1,       1],
       [      1,       2,       4, ...,   56084,       1,       1],
       [      2,       3,       5, ...,   62484,       1,       1],
       ...,
       [      4,       8,       7, ..., 1334719,       1,       0],
       [      4,       8,       8, ..., 1339563,       1,       1],
       [      3,       6,       4, ..., 1344544,       1,       1]])

In [5]:
mat1['trialinfo'][0]

array([    2,     3,     6,     2,     2,     1,     1, 45162, 45683,
       47433, 47703, 48209, 48779, 49284, 50308,     1,     1])

In [6]:
mat1['trialinfo'][1]

array([    1,     2,     4,     1,     2,     1,     2, 50808, 51322,
       53077, 53339, 53839, 54371, 54871, 56084,     1,     1])

In [7]:
mat1['trialinfo'][2]

array([    2,     3,     5,     2,     1,     1,     1, 56584, 57102,
       58852, 59120, 59627, 60209, 60708, 62484,     1,     1])

In [8]:
mat1['trial'] #(1,224)

array([array([[ -4.10919043,  -4.06128792,  -3.57010313, ..., -10.86775008,
               -12.17114197, -12.53634028],
              [ -6.29100525,  -5.23406347,  -3.25321401, ...,  -4.90553721,
                -4.55881157,  -3.83558736],
              [ -3.55608855,  -2.3965536 ,  -0.51341814, ...,  -7.07075359,
                -6.37294056,  -5.61396586],
              ...,
              [  2.71037747,   3.0933731 ,   2.9699286 , ...,   3.53163173,
                 4.9364774 ,   6.00598899],
              [ -1.32949074,  -2.52599939,  -3.96518807, ...,   9.44704003,
                 8.97916058,   8.59249654],
              [ -0.41675975,  -0.86901184,  -1.83941729, ...,   8.38767725,
                 8.68499657,   8.81306769]])                               ,
       array([[  0.19808806,   2.22051317,   4.45653688, ...,  -2.78204037,
                -4.36810474,  -5.7315336 ],
              [ -2.91400804,  -1.3306995 ,   0.49797725, ...,  -6.45152531,
                -8.3314345 , -10

In [9]:
mat1['trial']# (224, )

array([array([[ -4.10919043,  -4.06128792,  -3.57010313, ..., -10.86775008,
               -12.17114197, -12.53634028],
              [ -6.29100525,  -5.23406347,  -3.25321401, ...,  -4.90553721,
                -4.55881157,  -3.83558736],
              [ -3.55608855,  -2.3965536 ,  -0.51341814, ...,  -7.07075359,
                -6.37294056,  -5.61396586],
              ...,
              [  2.71037747,   3.0933731 ,   2.9699286 , ...,   3.53163173,
                 4.9364774 ,   6.00598899],
              [ -1.32949074,  -2.52599939,  -3.96518807, ...,   9.44704003,
                 8.97916058,   8.59249654],
              [ -0.41675975,  -0.86901184,  -1.83941729, ...,   8.38767725,
                 8.68499657,   8.81306769]])                               ,
       array([[  0.19808806,   2.22051317,   4.45653688, ...,  -2.78204037,
                -4.36810474,  -5.7315336 ],
              [ -2.91400804,  -1.3306995 ,   0.49797725, ...,  -6.45152531,
                -8.3314345 , -10

In [10]:
mat1['time'][0]

array([-1.   , -0.998, -0.996, ..., 10.246, 10.248, 10.25 ])

In [11]:
mat1['sampleinfo']

array([[  45183,   50808],
       [  50822,   56584],
       [  56602,   62984],
       [  63002,   68121],
       [  68133,   74034],
       [  74065,   80102],
       [  80127,   85509],
       [  85527,   91377],
       [  91396,   96852],
       [  96876,  101896],
       [ 101922,  107164],
       [ 107195,  112790],
       [ 112813,  118140],
       [ 118151,  123439],
       [ 123452,  128616],
       [ 128633,  133946],
       [ 133965,  139164],
       [ 139196,  144215],
       [ 144234,  149514],
       [ 149534,  154490],
       [ 154516,  159609],
       [ 159634,  164845],
       [ 164865,  171052],
       [ 171084,  176389],
       [ 176406,  181634],
       [ 181666,  186808],
       [ 186834,  192203],
       [ 192222,  197509],
       [ 200595,  205646],
       [ 205665,  210652],
       [ 210683,  215865],
       [ 215896,  221120],
       [ 221146,  226226],
       [ 226245,  231301],
       [ 231321,  236377],
       [ 236395,  241340],
       [ 241365,  246689],
 

In [12]:
mat1['cfg']

array((array(['fastica001', 'fastica002', 'fastica003', 'fastica005',
       'fastica006', 'fastica008', 'fastica009', 'fastica013',
       'fastica014', 'fastica018', 'fastica021', 'fastica026',
       'fastica027', 'fastica028', 'fastica030', 'fastica031',
       'fastica034', 'fastica037', 'fastica039', 'fastica045',
       'fastica049', 'fastica052', 'fastica058'], dtype=object), 'pedantic', 'overwrite', array(('compat', 'compat', 'compat', array(['C:\\Users\\magik\\Documents\\MATLAB\\fieldtrip-20191028\\external\\spm8',
       'C:\\Users\\magik\\Documents\\MATLAB\\fieldtrip-20191028\\external\\fastica',
       'C:\\Users\\magik\\Documents\\MATLAB\\fieldtrip-20191028\\external\\fastica'],
      dtype=object)),
      dtype=[('images', 'O'), ('stats', 'O'), ('signal', 'O'), ('cleanup', 'O')]), array((0,), dtype=[('noerase', 'O')]), array((array((array([ 1,  2,  3,  5,  6,  8,  9, 13, 14, 18, 21, 26, 27, 28, 30, 31, 34,
       37, 39, 45, 49, 52, 58], dtype=uint8), 'pedantic', 'overwr